[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "rust_minimal_kernel.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
